# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty

# Setup
title: Victor Johnson
tagline: ''
description: 'Just a software engineer living in Louisville, KY.'
url: https://vicjohnson.dev
baseurl: ''
collections:
    projects:
        output: true

# About/contact
author:
    name: Victor Johnson
    url: vicjohnson.dev
    email: vicjohnson1213@gmail.com

# Custom vars
version: 1.0.0
