# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty

# Setup
title: Victor Johnson
tagline: ''
description: 'Just a software engineer living in Austin, TX.'
url: https://vicjohnson1213.github.io
baseurl: ''
collections:
    projects:
        output: true

# About/contact
author:
    name: Victor Johnson
    url: vicjohnson1213.github.io
    email: vicjohnson1213@gmail.com

# Custom vars
version: 1.0.0
